name: Generate README stats (user-statistician)

on:
  schedule:   # diário 02h UTC (23h BRT)
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # para commitar SVGs

    steps:
      - uses: actions/checkout@v4

      # 1️⃣ Card geral
      - name: Stats card
        uses: cicirello/user-statistician@v1.4.0    # <- versão nova
        with:
          image-file: .github-stats/github_stats.svg
          colors: dark
          hide-keys: contributions,languages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_STATS_TOKEN }}

      # 2️⃣ Card de contribuições (equiv. streak)
      - name: Contributions card
        uses: cicirello/user-statistician@v1.4.0
        with:
          image-file: .github-stats/github_streak.svg
          colors: dark
          hide-keys: general,repositories,languages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_STATS_TOKEN }}

      # 3️⃣ Card de linguagens
      - name: Languages card
        uses: cicirello/user-statistician@v1.4.0
        with:
          image-file: .github-stats/top_languages.svg
          colors: dark
          hide-keys: general,repositories,contributions
        env:
          GITHUB_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
