# .github/workflows/stats.yml
name: Generate README stats

on:
  schedule:
    - cron: '0 2 * * *'   # todo dia às 02 h UTC
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Gera o SVG e faz o commit/push automático
      - uses: cicirello/user-statistician@v1
        with:
          token: ${{ secrets.GH_STATS_TOKEN }}   # PAT com Contents → Read-only
          image-file: .github-stats/userstats.svg
          include-title: true
          theme: dark           # temas: dark, radical, etc.
          commit-message: "chore(stats): atualizar SVGs"

