name: Generate README stats (curl)

on:
  schedule: [ { cron: '0 2 * * *' } ]
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4

      - name: Download stats card (privados incluídos)
    env:
      GH_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
    run: |
      mkdir -p .github-stats

      curl -L \
        "https://github-readme-stats.vercel.app/api?username=maxsbot&include_all_commits=true&count_private=true&theme=dark&hide_border=true&token=$GH_TOKEN" \
        -o .github-stats/github_stats.svg

      curl -L \
        "https://github-readme-streak-stats.herokuapp.com?user=maxsbot&include_all_commits=true&count_private=true&theme=dark&hide_border=true&token=$GH_TOKEN" \
        -o .github-stats/github_streak.svg

      curl -L \
        "https://github-readme-stats.vercel.app/api/top-langs/?username=maxsbot&layout=compact&theme=dark&hide_border=true&count_private=true&token=$GH_TOKEN" \
        -o .github-stats/top_languages.svg

      - name: Commit & push
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github-stats
          git commit -m "chore(stats): atualizar SVGs" || echo "nada a commitar"
          git push
