name: GitHub profile metrics

on:
  schedule:           # todo dia às 02 h UTC (23 h BRT)
    - cron: '0 2 * * *'
  workflow_dispatch:  # botão “Run workflow”

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # precisa commitar o SVG

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN}}
          user: maxsbot
          template: classic          # visual padrão (dark-aware)
          base: header, activity, community, repositories
          config_timezone: America/Maceio
          plugin_languages: yes
          plugin_languages_categories: programming
          plugin_lines: yes
          plugin_isocalendar: yes
          output_action: commit      # commita metrics.svg na raiz
